# Generated by Django 5.0.6 on 2024-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measuring_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
