# Generated by Django 5.0.6 on 2024-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bill_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
    ]
