# Generated by Django 5.0.6 on 2024-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bill_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='home.product'),
        ),
    ]
