# Generated by Django 5.0.6 on 2024-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bill_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
    ]
