# Generated by Django 5.0.6 on 2024-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bill_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='net_amount',
            field=models.IntegerField(default=0),
        ),
    ]
