# Generated by Django 5.0.6 on 2024-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_billitems_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_image', models.ImageField(blank=True, null=True, upload_to='qr_code/')),
            ],
        ),
    ]
