# Generated by Django 5.0.6 on 2024-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_firminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminfo',
            name='firm_gst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firminfo',
            name='firm_mob1',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='firminfo',
            name='firm_mob2',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
