# Generated by Django 5.0.6 on 2024-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_firminfo_firm_gst_firminfo_firm_mob1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminfo',
            name='firm_add',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
