# Generated by Django 5.0.6 on 2024-07-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_firminfo_firm_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitems',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bill'),
        ),
    ]
